/*------------------------------------------------------------------------------
 *******************************************************************************
 * COPYRIGHT Ericsson 2012
 *
 * The copyright to the computer program(s) herein is the property of
 * Ericsson Inc. The programs may be used and/or copied only with written
 * permission from Ericsson Inc. or in accordance with the terms and
 * conditions stipulated in the agreement/contract under which the
 * program(s) have been supplied.
 *******************************************************************************
 *----------------------------------------------------------------------------*/
package com.ericsson.mmepool.testsuite.eventGen;

import com.ericsson.xstream.apeventbeans.celltrace.INTERNAL_PROC_INITIAL_CTXT_SETUP;
import com.ericsson.xstream.apeventbeans.celltrace.INTERNAL_PROC_RRC_CONN_SETUP;
import com.ericsson.xstream.apeventbeans.celltrace.INTERNAL_PROC_S1_SIG_CONN_SETUP;

public class EventsCreator {

    public static final byte RRC_INITIAL_UE_IDENTITY_TYPE = (byte) 1;
    public static final byte[] RRC_INITIAL_UE_IDENTITY = new byte[] { 7, 9 };
    public static final byte RRC_RRC_ESTABL_CAUSE = (byte) 5;
    public static final byte S1_RRC_ESTABL_CAUSE = (byte) 31;
    public static final byte IC_P_3GPP_CAUSE = (byte) 61;
    public static final byte IC_P_3GPP_CAUSE_GROUP = (byte) 65;
    public static final byte[] IC_SERVING_PLMN_ID = new byte[] { 37, 39 };
    public static final int[] IC_EVENT_ARRAY_ERAB_SETUP_REQ_QCI = new int[] { 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216 };
    public static final byte[] IC_EVENT_ARRAY_ERAB_SETUP_REQ_PCI = new byte[] { 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36 };
    public static final byte[] IC_EVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE = new byte[] { 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56 };
    public static final byte[] IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP = new byte[] { 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76 };
    public static final byte[] IC_EVENT_ARRAY_ERAB_SETUP_REQ_ARP = new byte[] { 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96 };
    public static final byte[] IC_EVENT_ARRAY_ERAB_SETUP_REQ_PVI = new byte[] { 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116 };
    public static final byte[] IC_EVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE = new byte[] { 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46 };
    public static final byte[] IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE = new byte[] { 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66 };
    public static final byte DEFAULT_VALUE = (byte) -1;
    public static final byte SUCCESS = (byte) 0;
    public static final byte FAILURE = (byte) 1;

    public static INTERNAL_PROC_RRC_CONN_SETUP createRrcConnSetup(final long RAC_UE_REF, final long GLOBAL_CELL_ID, final byte RRC_RESULT) {
        final INTERNAL_PROC_RRC_CONN_SETUP rrcConnSetup = new INTERNAL_PROC_RRC_CONN_SETUP();
        rrcConnSetup.setRAC_UE_REF(RAC_UE_REF);
        rrcConnSetup.setGLOBAL_CELL_ID(GLOBAL_CELL_ID);
        rrcConnSetup.setRRC_RESULT(RRC_RESULT);

        rrcConnSetup.setINITIAL_UE_IDENTITY_TYPE(RRC_INITIAL_UE_IDENTITY_TYPE);
        rrcConnSetup.setINITIAL_UE_IDENTITY(RRC_INITIAL_UE_IDENTITY);
        rrcConnSetup.setRRC_ESTABL_CAUSE(RRC_RRC_ESTABL_CAUSE);
        return rrcConnSetup;
    }

    public static INTERNAL_PROC_S1_SIG_CONN_SETUP createS1SigConnSetup(final long RAC_UE_REF, final long GLOBAL_CELL_ID, final byte S1_SIG_CONN_RESULT) {
        final INTERNAL_PROC_S1_SIG_CONN_SETUP s1SigConnSetup = new INTERNAL_PROC_S1_SIG_CONN_SETUP();
        s1SigConnSetup.setRAC_UE_REF(RAC_UE_REF);
        s1SigConnSetup.setGLOBAL_CELL_ID(GLOBAL_CELL_ID);
        s1SigConnSetup.setS1_SIG_CONN_RESULT(S1_SIG_CONN_RESULT);

        s1SigConnSetup.setRRC_ESTABL_CAUSE(S1_RRC_ESTABL_CAUSE);
        return s1SigConnSetup;
    }

    public static INTERNAL_PROC_INITIAL_CTXT_SETUP createInitialCtxtSetup(final long RAC_UE_REF, final long GLOBAL_CELL_ID, final byte INITIAL_CTXT_RESULT,
            final byte[] IC_EVENT_ARRAY_ERAB_SETUP_RESULT) {
        final INTERNAL_PROC_INITIAL_CTXT_SETUP initialCtxtSetup = new INTERNAL_PROC_INITIAL_CTXT_SETUP();
        initialCtxtSetup.setRAC_UE_REF(RAC_UE_REF);
        initialCtxtSetup.setGLOBAL_CELL_ID(GLOBAL_CELL_ID);
        initialCtxtSetup.setINITIAL_CTXT_RESULT(INITIAL_CTXT_RESULT);

        initialCtxtSetup.setP_3GPP_CAUSE(IC_P_3GPP_CAUSE);
        initialCtxtSetup.setP_3GPP_CAUSE_GROUP(IC_P_3GPP_CAUSE_GROUP);
        initialCtxtSetup.setSERVING_PLMN_ID(IC_SERVING_PLMN_ID);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_RESULT_1(IC_EVENT_ARRAY_ERAB_SETUP_RESULT[0]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_RESULT_2(IC_EVENT_ARRAY_ERAB_SETUP_RESULT[1]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_RESULT_3(IC_EVENT_ARRAY_ERAB_SETUP_RESULT[2]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_RESULT_4(IC_EVENT_ARRAY_ERAB_SETUP_RESULT[3]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_RESULT_5(IC_EVENT_ARRAY_ERAB_SETUP_RESULT[4]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_RESULT_6(IC_EVENT_ARRAY_ERAB_SETUP_RESULT[5]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_RESULT_7(IC_EVENT_ARRAY_ERAB_SETUP_RESULT[6]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_RESULT_8(IC_EVENT_ARRAY_ERAB_SETUP_RESULT[7]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_RESULT_9(IC_EVENT_ARRAY_ERAB_SETUP_RESULT[8]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_RESULT_10(IC_EVENT_ARRAY_ERAB_SETUP_RESULT[9]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_RESULT_11(IC_EVENT_ARRAY_ERAB_SETUP_RESULT[10]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_RESULT_12(IC_EVENT_ARRAY_ERAB_SETUP_RESULT[11]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_RESULT_13(IC_EVENT_ARRAY_ERAB_SETUP_RESULT[12]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_RESULT_14(IC_EVENT_ARRAY_ERAB_SETUP_RESULT[13]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_RESULT_15(IC_EVENT_ARRAY_ERAB_SETUP_RESULT[14]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_RESULT_16(IC_EVENT_ARRAY_ERAB_SETUP_RESULT[15]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_QCI_1(IC_EVENT_ARRAY_ERAB_SETUP_REQ_QCI[0]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_QCI_2(IC_EVENT_ARRAY_ERAB_SETUP_REQ_QCI[1]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_QCI_3(IC_EVENT_ARRAY_ERAB_SETUP_REQ_QCI[2]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_QCI_4(IC_EVENT_ARRAY_ERAB_SETUP_REQ_QCI[3]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_QCI_5(IC_EVENT_ARRAY_ERAB_SETUP_REQ_QCI[4]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_QCI_6(IC_EVENT_ARRAY_ERAB_SETUP_REQ_QCI[5]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_QCI_7(IC_EVENT_ARRAY_ERAB_SETUP_REQ_QCI[6]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_QCI_8(IC_EVENT_ARRAY_ERAB_SETUP_REQ_QCI[7]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_QCI_9(IC_EVENT_ARRAY_ERAB_SETUP_REQ_QCI[8]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_QCI_10(IC_EVENT_ARRAY_ERAB_SETUP_REQ_QCI[9]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_QCI_11(IC_EVENT_ARRAY_ERAB_SETUP_REQ_QCI[10]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_QCI_12(IC_EVENT_ARRAY_ERAB_SETUP_REQ_QCI[11]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_QCI_13(IC_EVENT_ARRAY_ERAB_SETUP_REQ_QCI[12]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_QCI_14(IC_EVENT_ARRAY_ERAB_SETUP_REQ_QCI[13]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_QCI_15(IC_EVENT_ARRAY_ERAB_SETUP_REQ_QCI[14]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_QCI_16(IC_EVENT_ARRAY_ERAB_SETUP_REQ_QCI[15]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_ARP_1(IC_EVENT_ARRAY_ERAB_SETUP_REQ_ARP[0]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_ARP_2(IC_EVENT_ARRAY_ERAB_SETUP_REQ_ARP[1]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_ARP_3(IC_EVENT_ARRAY_ERAB_SETUP_REQ_ARP[2]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_ARP_4(IC_EVENT_ARRAY_ERAB_SETUP_REQ_ARP[3]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_ARP_5(IC_EVENT_ARRAY_ERAB_SETUP_REQ_ARP[4]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_ARP_6(IC_EVENT_ARRAY_ERAB_SETUP_REQ_ARP[5]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_ARP_7(IC_EVENT_ARRAY_ERAB_SETUP_REQ_ARP[6]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_ARP_8(IC_EVENT_ARRAY_ERAB_SETUP_REQ_ARP[7]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_ARP_9(IC_EVENT_ARRAY_ERAB_SETUP_REQ_ARP[8]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_ARP_10(IC_EVENT_ARRAY_ERAB_SETUP_REQ_ARP[9]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_ARP_11(IC_EVENT_ARRAY_ERAB_SETUP_REQ_ARP[10]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_ARP_12(IC_EVENT_ARRAY_ERAB_SETUP_REQ_ARP[11]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_ARP_13(IC_EVENT_ARRAY_ERAB_SETUP_REQ_ARP[12]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_ARP_14(IC_EVENT_ARRAY_ERAB_SETUP_REQ_ARP[13]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_ARP_15(IC_EVENT_ARRAY_ERAB_SETUP_REQ_ARP[14]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_ARP_16(IC_EVENT_ARRAY_ERAB_SETUP_REQ_ARP[15]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PCI_1(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PCI[0]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PCI_2(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PCI[1]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PCI_3(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PCI[2]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PCI_4(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PCI[3]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PCI_5(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PCI[4]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PCI_6(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PCI[5]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PCI_7(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PCI[6]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PCI_8(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PCI[7]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PCI_9(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PCI[8]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PCI_10(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PCI[9]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PCI_11(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PCI[10]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PCI_12(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PCI[11]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PCI_13(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PCI[12]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PCI_14(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PCI[13]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PCI_15(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PCI[14]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PCI_16(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PCI[15]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PVI_1(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PVI[0]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PVI_2(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PVI[1]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PVI_3(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PVI[2]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PVI_4(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PVI[3]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PVI_5(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PVI[4]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PVI_6(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PVI[5]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PVI_7(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PVI[6]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PVI_8(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PVI[7]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PVI_9(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PVI[8]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PVI_10(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PVI[9]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PVI_11(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PVI[10]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PVI_12(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PVI[11]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PVI_13(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PVI[12]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PVI_14(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PVI[13]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PVI_15(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PVI[14]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_REQ_PVI_16(IC_EVENT_ARRAY_ERAB_SETUP_REQ_PVI[15]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE_1(IC_EVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE[0]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE_2(IC_EVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE[1]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE_3(IC_EVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE[2]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE_4(IC_EVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE[3]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE_5(IC_EVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE[4]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE_6(IC_EVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE[5]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE_7(IC_EVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE[6]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE_8(IC_EVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE[7]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE_9(IC_EVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE[8]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE_10(IC_EVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE[9]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE_11(IC_EVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE[10]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE_12(IC_EVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE[11]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE_13(IC_EVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE[12]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE_14(IC_EVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE[13]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE_15(IC_EVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE[14]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE_16(IC_EVENT_ARRAY_ERAB_SETUP_ATT_ACC_TYPE[15]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE_1(IC_EVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE[0]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE_2(IC_EVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE[1]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE_3(IC_EVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE[2]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE_4(IC_EVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE[3]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE_5(IC_EVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE[4]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE_6(IC_EVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE[5]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE_7(IC_EVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE[6]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE_8(IC_EVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE[7]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE_9(IC_EVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE[8]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE_10(IC_EVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE[9]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE_11(IC_EVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE[10]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE_12(IC_EVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE[11]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE_13(IC_EVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE[12]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE_14(IC_EVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE[13]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE_15(IC_EVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE[14]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE_16(IC_EVENT_ARRAY_ERAB_SETUP_SUCC_ACC_TYPE[15]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP_1(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP[0]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP_2(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP[1]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP_3(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP[2]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP_4(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP[3]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP_5(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP[4]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP_6(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP[5]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP_7(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP[6]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP_8(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP[7]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP_9(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP[8]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP_10(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP[9]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP_11(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP[10]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP_12(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP[11]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP_13(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP[12]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP_14(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP[13]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP_15(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP[14]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP_16(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_GROUP[15]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_1(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE[0]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_2(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE[1]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_3(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE[2]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_4(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE[3]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_5(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE[4]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_6(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE[5]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_7(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE[6]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_8(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE[7]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_9(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE[8]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_10(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE[9]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_11(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE[10]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_12(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE[11]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_13(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE[12]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_14(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE[13]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_15(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE[14]);
        initialCtxtSetup.setEVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE_16(IC_EVENT_ARRAY_ERAB_SETUP_FAILURE_3GPP_CAUSE[15]);
        return initialCtxtSetup;
    }
}